### ISSUE TITLE
For Custom guard 'Admin' and 'Writer' logout is not clearing sessions when remember me is checked

### ISSUE THREAD

**Issue by asamamun** [fisayoafolayan/laravel-multiple-auth#3]
to resolve the issue i have added:
    public function logout(Request $request)
    {
        $this->guard()->logout();
        //custom code
        Auth::guard('admin')->logout();
        Auth::guard('writer')->logout();
        $request->session()->flush();
        $request->session()->regenerate();
        //custom code end     
        $request->session()->invalidate();
        return $this->loggedOut($request) ?: redirect('/');
    }
in Illuminate\Foundation\Auth\AuthenticatesUsers.php

**Comment by fisayoafolayan** [comment]
Hello @asamamun,

Unfortunately, I can't replicate this bug locally. Please do submit a PR if the problem still persists. 

Thanks for raising the issue 👍
